### ISSUE TITLE
Color mapping support

### ISSUE THREAD

**Issue by davidferlay** [skilld-labs/kaizen#10]
### Context

We developed functionality on one of last projects to map colors of theme in an administrable way, from drupal administration using color module

### Observed result

Functionality was appreciated by pm and client
It has been decided to use similar thing on all new projects as it provides valuable functionnality

### Expected result

So it makes sense to add color module support in theme, if that's the solution to use

### Todo

Implement color module support

**Comment by iberdinsky-skilld** [comment]
Better to follow that update. 
https://www.drupal.org/project/drupal/issues/788332
