### ISSUE TITLE
Define prethemed components list

### ISSUE THREAD

**Issue by iberdinsky-skilld** [skilld-labs/kaizen#105]
> Would be great to ge : breadcrumb.css, captions, comments, dropbutton, field, form, pager, menu, ui-dialog, ui-widget (iddn't check if already here or not)

```
we don't need forum
```

**Comment by iberdinsky-skilld** [comment]
we also need to avoid use jquery as is. better to create independent components. with jquery classes extends.

**Comment by davidferlay** [comment]
Updated list : 
- block
- breadcrumb
- buttons
- captions
- comments
- contextual
- dropbutton.component
- field
- form
- header
- help
- highlighted
- image-button
- item-list
- list-group
- list
- main-content
- menu
- messages
- node
- page-title
- pager
- panel
- password-suggestions
- primary-menu
- search-form
- search-results
- secondary-menu
- site-branding
- site-footer
- table
- tablesort-indicator
- tabs
- text-formatted
- ui-dialog
- ui.widget
- views

**Comment by iberdinsky-skilld** [comment]
- [ ] block
- [ ] breadcrumb
- [ ] buttons
- [ ] comments
- [ ] dropbutton.component
- [ ] field
- [ ] form
- [ ] header
- [ ] item-list
- [ ] list-group
- [ ] list
- [ ] main-content
- [ ] menu
- [ ] messages
- [ ] node
- [ ] page-title
- [ ] pager
- [ ] panel
- [ ] password-suggestions
- [ ] primary-menu
- [ ] secondary-menu
- [ ] site-branding
- [ ] site-footer
- [ ] table
- [ ] tablesort-indicator
- [ ] tabs
- [ ] text-formatted
- [ ] views

**Comment by koskinpark** [comment]
Wohoou 💥
