### ISSUE TITLE
Add line-clamp support 

### ISSUE THREAD

**Issue by iberdinsky-skilld** [skilld-labs/kaizen#14]
If browser supports `-webkit-clamp-lines` will be used trimCSS, else trimJs.
with breakpoints usage. to have breakpoint based config like:
```
  example: {
    selector: '.CSS_SELECTOR',
    trim: 1,
    breakpoints: {
      'large': 2
    }
  },
```

**Comment by iberdinsky-skilld** [comment]
i would better suggest to move it to npm package

**Comment by hog-seruj** [comment]
https://www.npmjs.com/package/@skilld/line-clamp
