### ISSUE TITLE
Research sass typography lib

### ISSUE THREAD

**Issue by iberdinsky-skilld** [skilld-labs/kaizen#23]
https://www.npmjs.com/package/typey has alternatives. and maybe we may add something better

**Comment by Megajack** [comment]
I did research about alternatives and checked next:
[sassline](https://sassline.com/)
[typi](https://github.com/zellwk/typi)
[Sassy-Gridlover](https://github.com/hiulit/Sassy-Gridlover)
[shevy](http://kyleshevlin.github.io/shevy/)

And none of these I didn't like. Some of them are quite complicated, some have useless extra features, that means we can lose time on their integration. 
I think Type is quite enough for our goals and everyone are well familiar with it.

**Comment by iberdinsky-skilld** [comment]
since no sass anymore. closing
