### ISSUE TITLE
Update sass lint

### ISSUE THREAD

**Issue by iberdinsky-skilld** [skilld-labs/kaizen#3]
Rework .sass-lint.yml

**Comment by koskinpark** [comment]
https://github.com/skilld-labs/kaizen/pull/37

**Comment by finnsky** [comment]
https://github.com/CSSLint/csslint/wiki/Disallow-outline:none should be added

**Comment by iberdinsky-skilld** [comment]
https://github.com/skilld-labs/kaizen/issues/3#issuecomment-465257849

**Comment by iberdinsky-skilld** [comment]
https://github.com/CSSLint/csslint/wiki/Disallow-outline:none

**Comment by iberdinsky-skilld** [comment]
no sass no sasslint
