### ISSUE TITLE
Remove modernizr dependency in core libraries in info file. 

### ISSUE THREAD

**Issue by iberdinsky-skilld** [skilld-labs/kaizen#42]
Since we have theme modernizr build we should enable same checks and override it in theme info.
https://cgit.drupalcode.org/drupal/tree/core/assets/vendor/modernizr/modernizr.min.js

**Comment by koskinpark** [comment]
I can't make it work with core modules that requires modernizr.
Also we have now issue with touchevent tests of latest modernizr, see

https://github.com/Modernizr/Modernizr/pull/2409
https://github.com/Modernizr/Modernizr/issues/2430

These changes are weird for me, which means you can't detect REAL touch screens now. Needs debug.

**Comment by andypost** [comment]
Related to fix in core https://www.drupal.org/project/drupal/issues/2168711
