### ISSUE TITLE
Add starterkit. Suggestions Topic

### ISSUE THREAD

**Issue by iberdinsky-skilld** [skilld-labs/kaizen#6]
Basic starterkit created in this PR https://github.com/skilld-labs/kaizen/pull/49

So fo next steps we need to have some kind of basic themed starterkit containing same build tools and some styles. We may use framework here. Let's disquss what can be base.

**Comment by iberdinsky-skilld** [comment]
https://materializecss.com/ i like it. but seems out of box it doesn't have some nice css features.

**Comment by Drintios** [comment]
This one https://tailwindcss.com/ might be cool as our approach is BEM this one is only based on utilities

**Comment by iberdinsky-skilld** [comment]
> This one https://tailwindcss.com/ might be cool as our approach is components based, this one is only based on utilities

looks nice.
