### ISSUE TITLE
add configs for drupal's blocks

### ISSUE THREAD

**Issue by koskinpark** [skilld-labs/kaizen#64]

**Comment by koskinpark** [comment]
https://github.com/skilld-labs/kaizen/pull/65

**Comment by iberdinsky-skilld** [comment]
@andypost is that blocks needed in basic? or it is ok to put it into themed version? 
since i don't feel we need 
https://github.com/skilld-labs/kaizen/pull/65/files#diff-46a07470f047490a2bed5be5555ac68eR13
`powered by` etc.

**Comment by iberdinsky-skilld** [comment]
added in primary theme
